name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      # Wow! https://github.community/t/sequence-of-instructions-in-cmd-shell-doesnt-work/16985
      - shell: cmd
        run: |
          :loop
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          set
          echo ------
          goto loop
